### ISSUE TITLE
Problem server

### ISSUE THREAD

**Issue by MXC48** [Crissium/SilverDict-mobile#5]
why does the app show me this ?![Screenshot_20231112-104834_SilverDict.png](https://github.com/Crissium/SilverDict-mobile/assets/123580315/7dd43706-7e4b-4e11-bc10-390bff06ebaa)

**Comment by Crissium** [comment]
The default server address is http://localhost:2628, so if you do not have a local SilverDict server running on your phone, it will show this alert. You could change the server address in Settings, or just set on up in Termux right on your Android device. Check this out: https://github.com/Crissium/SilverDict/wiki/android#running-the-server-on-android

**Comment by MXC48** [comment]
> The default server address is http://localhost:2628, so if you do not have a local SilverDict server running on your phone, it will show this alert. You could change the server address in Settings, or just set on up in Termux right on your Android device. Check this out: https://github.com/Crissium/SilverDict/wiki/android#running-the-server-on-android

does this mean I'll have another service running in the background?

**Comment by Crissium** [comment]
> does this mean I'll have another service running in the background?

Yes. This is only the mobile client. You have to have a server running, whether local or remote.

**Comment by MXC48** [comment]
> > does this mean I'll have another service running in the background?
> 
> Yes. This is only the mobile client. You have to have a server running, whether local or remote.

ok thanks for the application
