### ISSUE TITLE
[Feature Request] [Android] Themed / Monochrome launcher app icon support

### ISSUE THREAD

**Issue by sebastien46** [Crissium/SilverDict-mobile#6]
Starting with [TargetSDK 33](https://developer.android.com/about/versions/13), devices can call the [getMonochrome()](https://developer.android.com/reference/android/graphics/drawable/AdaptiveIconDrawable#getMonochrome()) function from the [AdaptiveIconDrawable](https://developer.android.com/reference/android/graphics/drawable/AdaptiveIconDrawable) class, which can enable the app to render a user-themed / monochromatic version of it's [Drawable](https://developer.android.com/reference/kotlin/android/graphics/drawable/Drawable) icon:

![](https://developer.android.com/static/guide/practices/ui_guidelines/images/adaptive-icon-monochrome.png)

[Developer Reference Documentation](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)

**Comment by Crissium** [comment]
Thanks for the tip! Actually I myself would also like the icon to be adaptive but did not know how to do it.

**Comment by Crissium** [comment]
The new version has been released. The adaptive icon started working on my Samsung (OneUI) device only after I did a clean re-installation.

**Comment by Crissium** [comment]
Sorry, I just tested on my Pixel emulator and saw what you had meant... Currently it looks like this:

![Screenshot_1700490430](https://github.com/Crissium/SilverDict-mobile/assets/91039086/f251b79f-ad5e-4119-8c57-605b0992b969)

I am still on Android 12, which does not support themed icons yet, and I hardly know anything about design. So any help would be appreciated.

Edit: OK I see the problem. Basically I need to supply the monochromatic version myself... Will do it later when I have more time.

**Comment by Crissium** [comment]
I just extracted the outline and turned it into a monochromatic version of the icon.

![Screenshot_1700738332](https://github.com/Crissium/SilverDict-mobile/assets/91039086/10d0cd69-1488-4886-b03d-ddeadb4f0604)
